#!/usr/bin/env bash
# update example.

# shellcheck disable=SC1091
# shellcheck disable=SC1090


./shelldoc --in shelldoc --out shelldoc.md --header "shelldoc docs" --desc "A simple utility for creating [Tomdoc](http://tomdoc.org/) style documentation for bash script." --access Public